[build]
  base = "packages/frontend"
  command = "pnpm build"
  publish = "dist"
  ignore = "[ $CONTEXT != 'deploy-preview' ] && exit 0 || exit 1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
